# Default initial efforts for panda's ros2_control fake system

initial_efforts:
  panda_finger_joint1: 0
  panda_joint1: 0.000000
  panda_joint2: -1.771364
  panda_joint3: -0.644000
  panda_joint4: 18.573574
  panda_joint5: 0.633846
  panda_joint6: 1.693690
  panda_joint7: -0.000000