# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# As explained at 
# https://moveit.picknik.ai/main/doc/examples/controller_configuration/controller_configuration_tutorial.html#example-controller-manager
# this configuration file configures an interface between the MoveIt! planning system
# and ROS2 controllers. The names provided here must match the names in ros2_controllers.yaml.
# When the moveit_manage_controllers move_group node's parameter is set to true,
# the ROS2 controllers are managed by MoveIt! according to the configurations here below.
moveit_simple_controller_manager:
  controller_names:
    - panda_arm_trajectory_controller
    - hand_controller
    - panda_impedance_controller

  panda_arm_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

  panda_impedance_controller:
    type: cartesian_control_msgs/FollowCartesianTrajectory
    action_ns: follow_cartesian_trajectory
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7


  hand_controller:
    type: GripperCommand
    joints:
      - panda_finger_joint1
    action_ns: gripper_cmd
    default: true