controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    panda_arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    panda_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    panda_forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    panda_impedance_controller:
      type: panda_impedance_controller/ImpedanceController



# panda_arm_trajectory_controller:
#   ros__parameters:
#     joints:
#       - panda_joint1
#       - panda_joint2
#       - panda_joint3
#       - panda_joint4
#       - panda_joint5
#       - panda_joint6
#       - panda_joint7
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity


panda_arm_trajectory_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
    gains:
      panda_joint1:
        p: 1000.0
        i: 100.0
        d: 10.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      panda_joint2:
        p: 1000.0
        i: 100.0
        d: 10.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      panda_joint3:
        p: 1000.0
        i: 100.0
        d: 10.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      panda_joint4:
        p: 1500.0
        i: 2000.0
        d: 25.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      panda_joint5:
        p: 100.0
        i: 10.0
        d: 1.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      panda_joint6:
        p: 100.0
        i: 10.0
        d: 1.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false
      panda_joint7:
        p: 100.0
        i: 10.0
        d: 1.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false



hand_controller:
  ros__parameters:
    joint: panda_finger_joint1

panda_forward_position_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
      - panda_finger_joint1
    interface_name: position

panda_forward_velocity_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    interface_name: velocity


panda_impedance_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    robot_base_link: "panda_link0"  # The base link of the robot to which all other links are referenced.
    end_effector_link: "panda_link8"  # The link representing the end effector of the robot.
    joint_model_group_name: "panda_arm"  # The name of the joint model group for which motion planning and control are performed.

    # Desired joint positions for the robot in radians. These positions represent the goal configuration of the robot's joints.
    desired_joint_positions:
      - 0.0         # Position of panda_joint1
      - -0.785398   # Position of panda_joint2
      - 0.0         # Position of panda_joint3
      - -2.35619    # Position of panda_joint4
      - 0.0         # Position of panda_joint5
      - 1.5708      # Position of panda_joint6
      - 0.785398    # Position of panda_joint7

    # Desired end-effector orientation in Roll-Pitch-Yaw (RPY) format.
    desired_orientation_rpy:
      roll: 3.141593   # Desired roll orientation in radians.
      pitch: 0.000008  # Desired pitch orientation in radians.
      yaw: 0.785398    # Desired yaw orientation in radians.
      # Corresponding quaternion in scalar-first notation: w: -0.000002, x: 0.923880, y: -0.382683, z: 0.000004

    # Impedance controller gains for different directions and orientations.
    gains:
      stiffness:
        x: 500000.0  # Stiffness gain for the X direction.
        y: 500000.0  # Stiffness gain for the Y direction.
        z: 500000.0  # Stiffness gain for the Z direction.
        orientation_x: 500.0  # Stiffness gain for rotation around the X-axis.
        orientation_y: 500.0  # Stiffness gain for rotation around the Y-axis.
        orientation_z: 500.0  # Stiffness gain for rotation around the Z-axis.
    
    gravity_compensation: false  # Disable gravity compensation in the controller.
    nullspace_stiffness: 8000.0  # Stiffness of the nullspace (configuration space not affecting the primary task).

    use_sim_time: true  # Enable the use of simulation time, typically used when running in a simulated environment.


